name: Build
on:
  push:
  schedule:
    - cron: '30 9 22 * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false
      - run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            arch-install-scripts \
            makepkg \
            pacman-package-manager
          sudo mkdir -p /etc/pacman.d
          echo 'Server = https://ca.us.mirror.archlinuxarm.org/$arch/$repo' | sudo tee /etc/pacman.d/mirrorlist
      - run: |
          sudo pacman-key --init
          # sudo pacman-key --recv-keys "$ARCHLINUXARM_PACKAGE_GPG"
          # sudo pacman-key --finger "$ARCHLINUXARM_PACKAGE_GPG"
          # sudo pacman-key --lsign-key "$ARCHLINUXARM_PACKAGE_GPG"
        env:
          ARCHLINUXARM_PACKAGE_GPG: 68B3537F39A313B3E574D06777193F152BDBE6A6
      - run: |
          sudo mkdir -p /rootfs
          sudo mount --bind /rootfs /rootfs
          sudo pacstrap -C pacman.conf -G -M /rootfs base base-devel archlinux-keyring archlinuxarm-keyring git openssh
      - run: sudo tar --xattrs cf rootfs.tar -C /rootfs .
      - uses: actions/upload-artifact@v4.6.1
        with:
          path: rootfs.tar
