name: Build
on:
  push:
  schedule:
    - cron: '30 9 22 * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false
      - name: Install Pacman
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends fakechroot fakeroot pacman-package-manager makepkg
      - name: Setup Pacman
        run: |
          sudo pacman-key --init 
          sudo pacman-key --keyserver keyserver.ubuntu.com --recv-keys "$ARCHLINUXARM_PACKAGE_GPG"
          sudo pacman-key --finger "$ARCHLINUXARM_PACKAGE_GPG"
          sudo pacman-key --lsign-key "$ARCHLINUXARM_PACKAGE_GPG"
        env:
          ARCHLINUXARM_PACKAGE_GPG: 68B3537F39A313B3E574D06777193F152BDBE6A6
      - run: |
          mkdir -p rootfs/var/lib/pacman/
          fakechroot -- fakeroot -- pacman -Sy -r rootfs \
            --noconfirm \
            --dbpath rootfs/var/lib/pacman \
            --config pacman.conf \
            --noscriptlet \
            base base-devel archlinux-keyring archlinuxarm-keyring git openssh
          fakechroot -- fakeroot -- chroot "$BUILDDIR" update-ca-trust
          fakechroot -- fakeroot -- chroot "$BUILDDIR" pacman-key --init
          fakechroot -- fakeroot -- chroot "$BUILDDIR" pacman-key --populate
          fakechroot -- fakeroot -- chroot "$BUILDDIR" /usr/bin/systemd-sysusers --root "/"
          sed -i -e 's/^root::/root:!:/' rootfs/etc/shadow
      - run: fakeroot -- tar --create --numeric-owner --xattrs --acls --exclude-from=exclude --file rootfs.tar --directory rootfs .
      - uses: actions/upload-artifact@v4.6.1
        with:
          path: rootfs.tar
