name: Build
on:
  push:
  schedule:
    - cron: '30 9 22 * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false
      - run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends pacman-package-manager arch-install-scripts
          echo 'Server = https://ca.us.mirror.archlinuxarm.org/$arch/$repo' | sudo tee /etc/pacman.d/mirrorlist
      - run: |
          sudo mkdir -p /rootfs
          sudo mount --bind /rootfs /rootfs
          sudo pacstrap -C /etc/pacman_arm.conf -G -M /rootfs base base-devel archlinux-keyring archlinuxarm-keyring git openssh
      - run: sudo tar --xattrs cf rootfs.tar -C /rootfs .
      - uses: actions/upload-artifact@v4.6.1
        with:
          path: rootfs.tar
